### ISSUE TITLE
Error: Symbol libxmljs_module not found.

### ISSUE THREAD

**Issue by shuhaowu** [vgrichina/libxmljs-easy#7]
node_modules/libxmljs-easy/node_modules/libxmljs/node_modules/bindings/bindings.js:79
            throw e
                  ^
    Error: Symbol libxmljs_module not found.
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at bindings (/home/shuhao/Dropbox/RandomProjects/monitoring-dashboard/node_modules/libxmljs-easy/node_modules/libxmljs/node_modules/bindings/bindings.js:74:15)
        at Object.<anonymous> (/home/shuhao/Dropbox/RandomProjects/monitoring-dashboard/node_modules/libxmljs-easy/node_modules/libxmljs/lib/bindings.js:1:99)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)

Getting that error when i load it. 

    $ node -v
    v0.10.15

**Comment by vgrichina** [comment]
@shuhaowu this shouldn't be relevant in latest version which depends on Node 0.12
